const products = [
  {
    id: 1,
    image: "https://5.imimg.com/data5/WC/IE/YH/ANDROID-86040604/prod-20200810-2031297210080910753376724-jpg.jpg",
    title: "Harvester Machine",
    description: "A high-performance harvester designed for large farms. It features advanced cutting technology, high fuel efficiency, and a comfortable operator cabin. The machine is equipped with a powerful engine and can harvest a wide variety of crops, including wheat, rice, and corn. Its ergonomic design ensures ease of use, and the durable construction guarantees long-lasting performance. Perfect for modern farming needs, this harvester significantly reduces labor costs and increases productivity.",
    price: "2500/day",
    category: "Machines",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Excellent machine! Increased our harvesting speed by 30%.",
        author: "John Doe",
        date: "2023-10-01",
      },
    ],
    specifications: [
      "Engine Power: 150 HP",
      "Fuel Type: Diesel",
      "Weight: 5000 kg",
      "Warranty: 2 years",
    ],
    relatedProducts: [2, 4],
  },
  {
    id: 2,
    image: "https://www.imarcgroup.com/blogs/files/0915ab2f-0eef-43b4-8b9b-4fc855a37590top-vegetable-seeds-companies.webp",
    title: "Organic Seeds",
    description: "Premium quality seeds for healthier and higher-yielding crops. These seeds are non-GMO and suitable for organic farming practices. They are carefully selected and tested to ensure high germination rates and resistance to common pests and diseases. Ideal for growing vegetables, fruits, and grains, these seeds promote sustainable agriculture and help farmers achieve better yields. Packed with essential nutrients, they ensure robust plant growth and improved soil health.",
    price: "700/kg",
    category: "Seeds",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Great germination rate and high yield.",
        author: "Robert Brown",
        date: "2023-09-20",
      },
    ],
    specifications: [
      "Type: Vegetable Seeds",
      "Germination Rate: 95%",
      "Suitable for: Organic Farming",
    ],
    relatedProducts: [3, 10, 28],
  },
  {
    id: 3,
    image: "https://i0.wp.com/media.premiumtimesng.com/wp-content/files/2013/12/Fertiliser-bags.jpg?fit=500%2C333&ssl=1",
    title: "Fertilizer Pack",
    description: "Eco-friendly fertilizer enriched with essential nutrients. Improves soil fertility and promotes healthy plant growth. This fertilizer is made from natural ingredients and is free from harmful chemicals, making it safe for both crops and the environment. It enhances soil structure, increases water retention, and boosts microbial activity. Suitable for all types of crops, it ensures higher yields and better-quality produce. Farmers can rely on this fertilizer for sustainable and organic farming practices.",
    price: "900/pack",
    category: "Fertilizers",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Improved my crop yield significantly.",
        author: "Alice Johnson",
        date: "2023-09-15",
      },
    ],
    specifications: [
      "Weight: 50 kg",
      "Nutrients: NPK 10-10-10",
      "Organic: Yes",
    ],
    relatedProducts: [2, 10, 28],
  },
  {
    id: 4,
    image: "https://www.deere.co.in/assets/images/region-1/products/tractors/john-deere-d-series-tractor.jpg",
    title: "Tractor Rental",
    description: "Powerful tractors available for rent to ease farming operations. Suitable for plowing, tilling, and transporting heavy loads. These tractors are equipped with advanced features like GPS navigation, hydraulic systems, and comfortable cabins. They are designed to handle tough terrains and heavy-duty tasks with ease. Farmers can save on upfront costs by renting these tractors for seasonal work. Reliable and efficient, they are a must-have for modern farming operations.",
    price: "3500/day",
    category: "Machines",
    availability: "In Stock",
    ratings: 4.8,
    reviews: [
      {
        comment: "Very powerful and easy to operate.",
        author: "Mike Taylor",
        date: "2023-09-25",
      },
    ],
    specifications: [
      "Engine Power: 75 HP",
      "Fuel Type: Diesel",
      "Weight: 3000 kg",
    ],
    relatedProducts: [1, 5, 14],
  },
  {
    id: 5,
    image: "https://img1.exportersindia.com/product_images/bc-full/2024/7/4750410/drip-irrigation-system-1721899449-7536346.jpeg",
    title: "Drip Irrigation Kit",
    description: "A complete irrigation system for water-efficient farming. Delivers water directly to plant roots, reducing water wastage. This kit includes high-quality pipes, emitters, and connectors for easy installation. It is suitable for a wide range of crops, including vegetables, fruits, and flowers. The system ensures uniform water distribution, prevents soil erosion, and promotes healthy plant growth. Farmers can save up to 50% on water usage while achieving higher yields.",
    price: "1500/set",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Saves water and improves crop yield.",
        author: "Sarah Lee",
        date: "2023-09-30",
      },
    ],
    specifications: [
      "Coverage: 1 acre",
      "Material: PVC",
      "Warranty: 1 year",
    ],
    relatedProducts: [9, 18, 29],
  },
  {
    id: 6,
    image: "https://t3.ftcdn.net/jpg/08/44/27/20/360_F_844272077_5SeapyCAOCjLOtD5dtBWcRvi5dLD71gP.jpg",
    title: "Pesticide Sprayer",
    description: "Easy-to-use sprayer for applying pesticides and fertilizers. Ensures even distribution and effective pest control. This sprayer is lightweight, durable, and designed for long-lasting performance. It features an adjustable nozzle for precise application and a comfortable handle for ease of use. Suitable for small to medium-sized farms, it helps farmers protect their crops from pests and diseases. Regular use of this sprayer can significantly improve crop health and yield.",
    price: "1200/unit",
    category: "Tools",
    availability: "In Stock",
    ratings: 4.4,
    reviews: [
      {
        comment: "Very efficient and easy to clean.",
        author: "David Wilson",
        date: "2023-09-28",
      },
    ],
    specifications: [
      "Capacity: 20 liters",
      "Material: Stainless Steel",
      "Weight: 5 kg",
    ],
    relatedProducts: [7, 16, 21],
  },
  {
    id: 7,
    image: "https://cdn.shopify.com/s/files/1/0409/2513/5001/files/Blog-Story-Images---2022---Gardening-5.jpg",
    title: "Farm Boots",
    description: "Durable boots for farm work. Made from high-quality materials to provide comfort and protection. These boots are waterproof, slip-resistant, and designed to withstand tough farming conditions. They feature reinforced toes and soles for added durability and safety. Perfect for long hours of work, they keep your feet dry and comfortable. Whether you're working in the fields or handling livestock, these boots are a reliable choice for farmers.",
    price: "1500/set",
    category: "Clothing",
    availability: "In Stock",
    ratings: 4.3,
    reviews: [
      {
        comment: "Very comfortable and durable.",
        author: "Emily Davis",
        date: "2023-09-22",
      },
    ],
    specifications: [
      "Material: Rubber",
      "Size: 7-12",
      "Waterproof: Yes",
    ],
    relatedProducts: [6, 16, 21],
  },
  {
    id: 8,
    image: "https://www.thrive.org.uk/files/images/Get-gardening/_1200x600_crop_center-center_none/Compost-in-a-wooden-frame-compost-bin.jpg",
    title: "Compost Bin",
    description: "Eco-friendly compost bin for waste recycling. Helps convert organic waste into nutrient-rich compost. This bin is made from durable plastic and features aeration holes for proper decomposition. It is easy to assemble and maintain, making it ideal for home gardeners and small-scale farmers. The compost produced can be used to enrich soil and promote healthy plant growth. A sustainable solution for managing organic waste and improving soil fertility.",
    price: "1200/unit",
    category: "Composting",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Great for recycling kitchen waste.",
        author: "Chris Evans",
        date: "2023-09-18",
      },
    ],
    specifications: [
      "Capacity: 100 liters",
      "Material: Plastic",
      "Weight: 10 kg",
    ],
    relatedProducts: [3, 10, 28],
  },
  {
    id: 9,
    image: "https://www.tatapowersolar.com/wp-content/uploads/2021/09/22073521/solar-warer-pump-banner-mob.jpg",
    title: "Solar Water Pump",
    description: "A solar-powered pump for sustainable irrigation. Reduces electricity costs and is environmentally friendly. This pump is designed to operate efficiently in remote areas with limited access to electricity. It features a high-capacity motor and durable solar panels for reliable performance. Farmers can use it to irrigate fields, fill water tanks, and supply water to livestock. A cost-effective and eco-friendly solution for modern farming needs.",
    price: "5000/unit",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Works great in remote areas.",
        author: "Laura Green",
        date: "2023-09-10",
      },
    ],
    specifications: [
      "Power: 5 HP",
      "Solar Panel Included: Yes",
      "Warranty: 2 years",
    ],
    relatedProducts: [5, 18, 29],
  },
  {
    id: 10,
    image: "https://m.media-amazon.com/images/I/51m7fwkmVkL._AC_UF350,350_QL80_.jpg",
    title: "Organic Manure",
    description: "100% organic manure to boost soil fertility. Suitable for all types of crops and improves soil health. This manure is made from natural ingredients and is free from harmful chemicals. It enhances soil structure, increases water retention, and promotes microbial activity. Farmers can use it to improve crop yields and produce healthier, more nutritious food. A must-have for organic farming and sustainable agriculture.",
    price: "800/bag",
    category: "Fertilizers",
    availability: "In Stock",
    ratings: 4.4,
    reviews: [
      {
        comment: "Improved my soil quality significantly.",
        author: "Mark Johnson",
        date: "2023-09-12",
      },
    ],
    specifications: [
      "Weight: 50 kg",
      "Organic: Yes",
      "Nutrients: NPK 5-5-5",
    ],
    relatedProducts: [2, 3, 8],
  },
  {
    id: 11,
    image: "https://rukminim2.flixcart.com/image/850/1000/l5e81ow0/garden-tool-set/s/y/q/sh01-hand-weeder-without-pipe-1-hectare-original-imagg3aghybmvytx.jpeg?q=20&crop=false",
    title: "Hand Weeder",
    description: "An essential tool for manual weeding in farms. Lightweight and easy to use, perfect for small-scale farming. This weeder is designed to remove weeds efficiently without damaging crops. It features a sharp blade and an ergonomic handle for comfortable use. Farmers can save time and effort by using this tool for regular weeding tasks. A must-have for maintaining clean and healthy fields.",
    price: "400/unit",
    category: "Tools",
    availability: "In Stock",
    ratings: 4.2,
    reviews: [
      {
        comment: "Very effective for removing weeds.",
        author: "Tom Harris",
        date: "2023-09-14",
      },
    ],
    specifications: [
      "Material: Stainless Steel",
      "Weight: 1.5 kg",
      "Handle: Ergonomic Design",
    ],
    relatedProducts: [6, 16, 21],
  },
  {
    id: 12,
    image: "https://www.trees.com/wp-content/uploads/2019/10/small-greenhouse-kit.jpg",
    title: "Greenhouse Kit",
    description: "A mini greenhouse for year-round cultivation. Protects plants from extreme weather and pests. This kit includes a sturdy frame, UV-resistant cover, and ventilation windows. It is easy to assemble and suitable for growing vegetables, flowers, and herbs. Farmers can extend their growing season and improve crop quality with this greenhouse. A great investment for small-scale and hobby farmers.",
    price: "7000/set",
    category: "Greenhouse",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Perfect for growing vegetables in winter.",
        author: "Linda White",
        date: "2023-09-08",
      },
    ],
    specifications: [
      "Size: 10x20 ft",
      "Material: Polycarbonate",
      "Warranty: 1 year",
    ],
    relatedProducts: [5, 18, 29],
  },
  {
    id: 13,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/PortableWaterTank.jpg/1200px-PortableWaterTank.jpg",
    title: "Portable Water Tank",
    description: "A lightweight tank for water storage on farms. Ideal for irrigation and livestock watering. This tank is made from durable plastic and features a large capacity for storing water. It is easy to transport and set up, making it perfect for remote farming areas. Farmers can use it to ensure a steady water supply for their crops and animals. A reliable solution for water management in agriculture.",
    price: "2000/unit",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.3,
    reviews: [
      {
        comment: "Very durable and easy to move around.",
        author: "Steve Brown",
        date: "2023-09-05",
      },
    ],
    specifications: [
      "Capacity: 1000 liters",
      "Material: Plastic",
      "Weight: 15 kg",
    ],
    relatedProducts: [5, 9, 29],
  },
  {
    id: 14,
    image: "https://5.imimg.com/data5/IA/VV/GQ/SELLER-2407540/six-row-rigid-cultivator-seed-cum-fertilizer-drill-500x500.JPG",
    title: "Automatic Seeder",
    description: "Efficient seeding tool for high crop yield. Ensures uniform seed distribution and reduces manual labor. This seeder is designed to handle a variety of seeds and soil types. It features adjustable settings for precise seeding and a durable construction for long-lasting use. Farmers can save time and improve planting accuracy with this tool. A must-have for modern farming operations.",
    price: "3500/unit",
    category: "Machines",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Saves time and improves seeding accuracy.",
        author: "Rachel Green",
        date: "2023-09-03",
      },
    ],
    specifications: [
      "Seed Capacity: 10 kg",
      "Power: Electric",
      "Weight: 20 kg",
    ],
    relatedProducts: [1, 4, 5],
  },
  {
    id: 15,
    image: "https://m.media-amazon.com/images/I/717ssKU1GCL._AC_UF1000,1000_QL80_.jpg",
    title: "Mulching Sheet",
    description: "Plastic mulching sheets for better water retention. Helps control weeds and maintain soil temperature. These sheets are made from high-quality polyethylene and are UV-resistant for long-lasting use. They are easy to install and suitable for a wide range of crops. Farmers can improve soil health and crop yield by using these sheets. A cost-effective solution for sustainable farming.",
    price: "1000/roll",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.4,
    reviews: [
      {
        comment: "Improved my crop yield significantly.",
        author: "Paul Walker",
        date: "2023-08-30",
      },
    ],
    specifications: [
      "Size: 4x100 ft",
      "Material: Polyethylene",
      "Color: Black",
    ],
    relatedProducts: [5, 18, 29],
  },
  {
    id: 16,
    image: "https://media.diy.com/is/image/KingfisherDigital/vonhaus-garden-tools-set-15pc-heavy-duty-gardening-hand-tool-kit-steel-wooden-tools-portable-bag-gift-for-men-women~5056115779671_04c_MP?$MOB_PREV$&$width=600&$height=600",
    title: "Hoe Tool Set",
    description: "A comprehensive collection of professional-grade hoe tools designed for serious farmers and gardeners. This durable set includes multiple specialized tools for efficient digging, precise weeding, and careful planting across various soil types. Each tool features ergonomic wooden handles and high-quality stainless steel heads that resist corrosion and maintain sharpness through extended use. The complete kit comes in a portable carrying case for easy transportation and storage, making it perfect for both small garden plots and larger agricultural operations. An essential investment for anyone looking to enhance their farming productivity.",
    price: "900/set",
    category: "Tools",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Great value for money.",
        author: "Emma Watson",
        date: "2023-08-28",
      },
    ],
    specifications: [
      "Tools Included: 5",
      "Material: Stainless Steel",
      "Weight: 3 kg",
    ],
    relatedProducts: [6, 7, 21],
  },
  {
    id: 17,
    image: "https://m.media-amazon.com/images/I/61-i8XAs6YL._AC_UF1000,1000_QL80_.jpg",
    title: "Soil Moisture Meter",
    description: "This advanced digital soil moisture meter delivers precise readings to help optimize your irrigation strategy for all types of crops. The high-sensitivity probes measure moisture levels at multiple soil depths, providing comprehensive data to prevent both overwatering and underwatering conditions. Features an easy-to-read digital display with color-coded zones indicating ideal moisture levels for different plant varieties. The weatherproof design ensures reliable operation in all farm conditions, while the long-lasting battery provides months of continuous use. Perfect for modern farmers seeking to conserve water resources while maximizing yield through data-driven agriculture practices.",
    price: "1200/unit",
    category: "Tools",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Very accurate and easy to use.",
        author: "Daniel Lee",
        date: "2023-08-25",
      },
    ],
    specifications: [
      "Measurement Range: 0-100%",
      "Battery: Included",
      "Weight: 0.5 kg",
    ],
    relatedProducts: [5, 18, 29],
  },
  {
    id: 18,
    image: "https://plantlane.com/cdn/shop/products/71fb_h9ztL._SL1280.jpg?v=1681898174",
    title: "Irrigation Timer",
    description: "Transform your irrigation system with this intelligent programmable timer that brings precision and automation to farm water management. This smart device allows you to create customized watering schedules for different zones based on crop needs, soil conditions, and weather patterns. The intuitive interface enables easy programming of multiple daily cycles with adjustable duration and flow rates. Compatible with most standard irrigation setups including drip systems, sprinklers, and soaker hoses. Features weather-sensing capabilities that automatically adjust watering schedules during rainy periods to prevent waste. The perfect solution for busy farmers looking to optimize water usage while maintaining ideal growing conditions.",
    price: "1800/unit",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Works perfectly with my drip irrigation system.",
        author: "Sophia Martinez",
        date: "2023-08-22",
      },
    ],
    specifications: [
      "Programmable: Yes",
      "Battery: Included",
      "Weight: 0.3 kg",
    ],
    relatedProducts: [5, 9, 29],
  },
  {
    id: 19,
    image: "https://www.greenproventures.com/wp-content/uploads/2020/06/Choosing-the-Right-Shade-Net-Knitted-or-Woven-GreenPro-India.jpg",
    title: "Shade Net",
    description: "This premium agricultural shade net provides essential protection for sensitive crops against harsh sunlight and extreme weather conditions. Engineered with UV-stabilized polyethylene material, it creates optimal microclimate conditions by reducing temperatures by up to 15°C while still allowing sufficient light penetration for photosynthesis. The specialized knitted construction ensures excellent air circulation while preventing heat buildup, significantly reducing plant stress and water evaporation. Highly durable and resistant to tearing, this shade net maintains its protective properties for multiple growing seasons even in challenging environments. The versatile design makes it suitable for various applications including greenhouse covers, nursery shading, and field crop protection.",
    price: "2500/roll",
    category: "Greenhouse",
    availability: "In Stock",
    ratings: 4.4,
    reviews: [
      {
        comment: "Great for protecting delicate plants.",
        author: "Michael Brown",
        date: "2023-08-20",
      },
    ],
    specifications: [
      "Size: 10x50 ft",
      "Material: Polyethylene",
      "Shade Percentage: 50%",
    ],
    relatedProducts: [12, 15, 29],
  },
  {
    id: 20,
    image: "https://img.feedstrategy.com/files/base/wattglobalmedia/all/image/2019/08/fs.Dairy-cows-fed-canola-meal.png?auto=format%2Ccompress&fit=max&q=70&w=1200",
    title: "Cow Feed",
    description: "This scientifically formulated premium dairy cattle feed is designed to maximize milk production while maintaining optimal health for your livestock. The balanced nutritional profile includes high-quality proteins, essential vitamins, and targeted mineral supplements that support immune function, reproductive health, and metabolic efficiency. Each batch undergoes strict quality control testing to ensure consistent nutrient content and eliminate contaminants. The optimized fiber-to-carbohydrate ratio promotes healthy rumen function and improves digestibility, resulting in better feed conversion rates and reduced waste. Regular feeding has been shown to increase milk yields by up to 15% while enhancing milk quality parameters including fat and protein content. An ideal choice for serious dairy farmers focused on productivity and animal welfare.",
    price: "1300/bag",
    category: "Animal Feed",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "My cows love it! Milk production increased.",
        author: "Olivia Davis",
        date: "2023-08-18",
      },
    ],
    specifications: [
      "Weight: 50 kg",
      "Ingredients: Corn, Soybean, Vitamins",
      "Suitable for: Dairy Cows",
    ],
    relatedProducts: [10, 27, 28],
  },
  {
    id: 21,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwTb1wtUXqE0X_sk5NxISexHlLVChPTImJOB-EJAm8VopUJomBKwoUNZMt3Q34D8YaOQw&usqp=CAU",
    title: "Garden Gloves",
    description: "These high-quality protective gloves are designed for farm and gardening work. Made from durable leather, they offer superior comfort and protection against thorns, rough surfaces, and chemicals. The gloves are waterproof, ensuring hands stay dry in wet conditions. With a snug fit and breathable material, they provide flexibility for long working hours. Ideal for farmers, gardeners, and landscapers, these gloves help prevent blisters and hand fatigue. Their reinforced stitching enhances durability, making them a long-lasting investment. Whether pruning, digging, or planting, these gloves offer excellent grip and safety.",
    price: "500/pair",
    category: "Clothing",
    availability: "In Stock",
    ratings: 4.3,
    reviews: [
      {
        comment: "Very comfortable and durable.",
        author: "Ethan Clark",
        date: "2023-08-15",
      },
    ],
    specifications: [
      "Material: Leather",
      "Size: Medium",
      "Waterproof: Yes",
    ],
    relatedProducts: [6, 7, 16],
  },
  {
    id: 22,
    image: "https://theoceangroup.co.in/wp-content/uploads/2024/05/Ocean-Rainwater-Harvester-diagram.jpg",
    title: "Rainwater Harvester",
    description: "A highly efficient rainwater collection system designed for farms to conserve water and reduce dependence on external sources. This harvester can store up to 5000 liters, making it ideal for irrigation and livestock needs. Made from high-quality plastic, it is lightweight yet sturdy, ensuring long-term durability. The system is easy to install and requires minimal maintenance. By utilizing natural rainwater, farmers can cut down water costs and ensure a sustainable supply throughout the year. Its eco-friendly design supports responsible water management.",
    price: "6000/unit",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Great for water conservation.",
        author: "Ava Wilson",
        date: "2023-08-12",
      },
    ],
    specifications: [
      "Capacity: 5000 liters",
      "Material: Plastic",
      "Weight: 50 kg",
    ],
    relatedProducts: [5, 9, 29],
  },
  {
    id: 23,
    image: "https://www.staticsystems.in/assets/img/ser/electric%20fence%20-%202.jpeg",
    title: "Electric Fencing",
    description: "This electric fence system provides advanced security for farms by keeping intruders and wild animals away from crops and livestock. It operates at a powerful 5000V, offering a reliable barrier without harming animals. The fence covers up to 1 km, making it suitable for large farms. With a solar-powered energy source, it is cost-effective and eco-friendly. Designed for easy installation, this fencing system helps farmers protect their property with minimal effort. Its durable construction ensures it can withstand extreme weather conditions.",
    price: "5000/set",
    category: "Security",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Very effective and easy to install.",
        author: "Noah Taylor",
        date: "2023-08-10",
      },
    ],
    specifications: [
      "Voltage: 5000V",
      "Coverage: 1 km",
      "Power Source: Solar",
    ],
    relatedProducts: [24, 25, 26],
  },
  {
    id: 24,
    image: "https://agrivijay.com/wp-content/uploads/2022/06/124.jpg",
    title: "Solar Dryer",
    description: "An innovative solar-powered dryer designed to preserve produce and extend shelf life. Ideal for drying fruits, vegetables, and grains, this device reduces post-harvest losses. Made from stainless steel, it ensures hygienic food processing. With a 50 kg capacity, farmers can process large batches efficiently. The solar-powered operation makes it cost-effective and environmentally friendly. Its easy-to-use design allows for hassle-free drying with consistent results.",
    price: "4500/unit",
    category: "Processing",
    availability: "In Stock",
    ratings: 4.4,
    reviews: [
      {
        comment: "Works great for drying fruits and vegetables.",
        author: "Mia Anderson",
        date: "2023-08-08",
      },
    ],
    specifications: [
      "Capacity: 50 kg",
      "Material: Stainless Steel",
      "Power Source: Solar",
    ],
    relatedProducts: [9, 22, 29],
  },
  {
    id: 25,
    image: "https://s3.toolsvilla.com/products-melastysinglemilkingmachineforcow/1728279647131/1728280504853-watmrkA.webp",
    title: "Portable Milking Machine",
    description: "A highly efficient automatic milking machine that enhances dairy farm operations. This electric-powered unit simplifies the milking process, reducing labor costs and improving hygiene. With a 10-liter capacity, it ensures a steady milk collection process. The machine is easy to clean and maintain, making it a must-have for dairy farmers. Its compact and portable design allows for easy transportation and storage.",
    price: "8000/unit",
    category: "Machines",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Very efficient and easy to clean.",
        author: "James Brown",
        date: "2023-08-05",
      },
    ],
    specifications: [
      "Capacity: 10 liters",
      "Power: Electric",
      "Weight: 15 kg",
    ],
    relatedProducts: [20, 27, 28],
  },
  {
    id: 26,
    image: "https://m.media-amazon.com/images/I/71aw35OZxPL.jpg",
    title: "Beekeeping Kit",
    description: "This comprehensive beekeeping kit includes everything needed to start and maintain a beehive. The Langstroth hive design ensures easy bee management and honey harvesting. The kit comes with five essential tools, including a smoker and a hive tool. Protective gear is also included, ensuring safety while handling bees. This kit is perfect for beginners and experienced beekeepers alike.",
    price: "5500/set",
    category: "Beekeeping",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Perfect for beginners.",
        author: "Lily Evans",
        date: "2023-08-03",
      },
    ],
    specifications: [
      "Hive Type: Langstroth",
      "Tools Included: 5",
      "Protective Gear: Yes",
    ],
    relatedProducts: [23, 24, 25],
  },
  {
    id: 27,
    image: "https://www.feed-pellet-mill.com/wp-content/uploads/2018/08/crushing-poultry-feed-pellets.jpg",
    title: "Animal Feed Grinder",
    description: "This high-capacity machine is designed for grinding livestock feed efficiently. With a grinding capacity of 100 kg per hour, it ensures uniform feed size for better digestion. Powered by electricity, it delivers consistent performance with minimal manual effort. Its durable design ensures longevity and reliable operation. Ideal for poultry, cattle, and other livestock farmers.",
    price: "7000/unit",
    category: "Machines",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Very efficient and durable.",
        author: "William Johnson",
        date: "2023-08-01",
      },
    ],
    specifications: [
      "Capacity: 100 kg/hour",
      "Power: Electric",
      "Weight: 50 kg",
    ],
    relatedProducts: [20, 25, 28],
  },
  {
    id: 28,
    image: "https://cdn.mos.cms.futurecdn.net/LXNSxTKXh279Lmg7pnNvUn.jpg",
    title: "Organic Pesticides",
    description: "A natural and eco-friendly pesticide solution for effective crop protection. This 1-liter bottle contains organic ingredients that target pests like aphids and caterpillars. Safe for humans, animals, and the environment, this pesticide supports sustainable farming. Its easy-to-apply formula ensures long-lasting protection for crops. Ideal for organic farms and environmentally conscious growers.",
    price: "900/bottle",
    category: "Pesticides",
    availability: "In Stock",
    ratings: 4.4,
    reviews: [
      {
        comment: "Works great and is eco-friendly.",
        author: "Sophie Brown",
        date: "2023-07-28",
      },
    ],
    specifications: [
      "Volume: 1 liter",
      "Organic: Yes",
      "Target Pests: Aphids, Caterpillars",
    ],
    relatedProducts: [2, 3, 10],
  },
  {
    id: 29,
    image: "https://regaber.com/wp-content/uploads/2017/11/1711Regaber_Noticias_Riego_por_Goteo_Cultivo-700x321.jpg",
    title: "Irrigation Pipes",
    description: "These high-quality PVC pipes are perfect for farm irrigation, ensuring efficient water distribution. Each set includes 100 meters of durable, weather-resistant piping with a 2-inch diameter. Designed to minimize water wastage, they improve irrigation efficiency and crop yield. Easy to install and maintain, they are an essential investment for modern farms.",
    price: "2200/set",
    category: "Irrigation",
    availability: "In Stock",
    ratings: 4.5,
    reviews: [
      {
        comment: "Very durable and easy to install.",
        author: "Ethan Wilson",
        date: "2023-07-25",
      },
    ],
    specifications: [
      "Length: 100 meters",
      "Material: PVC",
      "Diameter: 2 inches",
    ],
    relatedProducts: [5, 9, 18],
  },
  {
    id: 30,
    image: "https://m.media-amazon.com/images/I/41MSChSzzxL._AC_UF1000,1000_QL80_.jpg",
    title: "Greenhouse Polythene Film",
    description: "Premium UV-stabilized greenhouse covering film that creates optimal growing conditions for your plants. This high-grade polyethylene film offers exceptional light diffusion properties that reduce plant shadowing while maintaining ideal light transmission for photosynthesis. The thermal properties help retain heat during night hours and cool periods, extending your growing season significantly. Engineered with multiple layers for enhanced durability, this film resists tearing and provides up to 5 years of reliable service even in harsh weather conditions. The anti-drip technology prevents condensation from forming droplets that could damage plants, instead allowing moisture to flow down the sides. Installation is straightforward with reinforced edges that work perfectly with standard greenhouse frame systems. This covering creates the perfect microclimate for year-round growing success.",
    price: "3500/roll",
    category: "Greenhouse",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Dramatically extended my growing season in a cold climate.",
        author: "Thomas Gardner",
        date: "2023-09-15",
      },
    ],
    specifications: [
      "Size: 20x100 ft",
      "Thickness: 6 mil",
      "UV Protection: Yes",
      "Light Transmission: 90%",
      "Warranty: 5 years"
    ],
    relatedProducts: [12, 15, 19],
  },
  {
    id: 31,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/3/292833239/DP/RE/TG/966103/05-500x500.jpg",
    title: "Poultry Incubator",
    description: "State-of-the-art digital egg incubator designed for maximum hatching success and ease of use. This fully automatic system maintains precise temperature and humidity levels through its intelligent microcomputer control system. The clear viewing window and LED display allow for easy monitoring without disturbing the incubation environment. Built-in egg turning mechanism automatically rotates eggs at optimal intervals, eliminating the need for manual turning and ensuring even development. The humidity alarm alerts you when water levels need replenishing, while the temperature deviation alarm ensures conditions remain stable. This incubator accommodates various egg sizes from quail to duck, with specialized egg trays included. Energy-efficient operation keeps electricity costs low even during extended hatching periods. Perfect for small-scale poultry farmers looking to expand their flock reliably.",
    price: "4200/unit",
    category: "Livestock",
    availability: "In Stock",
    ratings: 4.8,
    reviews: [
      {
        comment: "Consistently achieving 90% hatching success rate with this machine.",
        author: "Rebecca Poultry",
        date: "2023-10-05",
      },
    ],
    specifications: [
      "Capacity: 48 chicken eggs",
      "Temperature Range: 37.5-38.5°C",
      "Humidity Control: Yes",
      "Power: 80W",
      "Automatic Egg Turner: Yes"
    ],
    relatedProducts: [20, 25, 27],
  },
  {
    id: 32,
    image: "https://www.croptracker.com/images/blog/10_Emerging_AgTech_Innovations/sprayer_drone500.jpg",
    title: "Agricultural Drone",
    description: "Revolutionary farming drone equipped with multispectral imaging technology for comprehensive field monitoring and analysis. This advanced aerial system captures detailed crop health data through specialized cameras that detect variations in plant vigor invisible to the human eye. The efficient spraying system allows for precise application of fertilizers or pesticides, reducing chemical usage by up to 30% compared to traditional methods. With automated flight planning, the drone can cover up to 30 acres per hour while maintaining consistent altitude and overlap for perfect data collection. The water-resistant design ensures operation in varying weather conditions, while the foldable structure facilitates easy transportation between fields. Data synchronizes wirelessly with the included farm management software, providing actionable insights on crop development, stress areas, and irrigation needs. An essential technology for modern precision agriculture that quickly pays for itself through improved crop management.",
    price: "75000/unit",
    category: "Technology",
    availability: "Limited Stock",
    ratings: 4.9,
    reviews: [
      {
        comment: "Transformed how we monitor our 200-acre farm. Identified irrigation issues we couldn't see from the ground.",
        author: "James Technology",
        date: "2023-11-10",
      },
    ],
    specifications: [
      "Flight Time: 25 minutes",
      "Camera Resolution: 12MP RGB + Multispectral",
      "Spray Capacity: 10L",
      "Coverage: 30 acres/hour",
      "Battery: Rechargeable Lithium",
      "Software: Included"
    ],
    relatedProducts: [17, 18, 22],
  },
  {
    id: 33,
    image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjhlps9wi11iPZrfRxsNnqJN-ze5xRxGrOeXtvf_B-HfdNPPH2p5UfanZybmZjmSTuzfgXYB2cNdjVx9w9-d7clzQD_oWewYe4ByyWEhoMb8xout9V8V77I2cJQXUubdve79t3dLnPs86cv/s1600/fullsizeoutput_1ffe.jpeg",
    title: "Composting System",
    description: "Professional-grade composting system designed to efficiently transform farm waste into valuable organic fertilizer. This three-bin design allows for continuous composting at different stages, enabling you to have finished compost available while new material is being processed. Constructed from recycled, weather-resistant materials, this system will withstand years of outdoor use without deteriorating. The adjustable ventilation panels optimize airflow for faster decomposition while the secure lids prevent excess moisture during rainy periods and deter pests. Each bin features a convenient front access door for easy compost removal when ready. The system comes with a comprehensive guide covering optimal material ratios, turning schedules, and troubleshooting tips for perfect compost every time. By converting waste into nutrient-rich soil amendment, this system helps close the nutrient cycle on your farm while reducing disposal costs and environmental impact.",
    price: "9500/unit",
    category: "Sustainable Farming",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Produces amazing quality compost in about half the time of our previous method.",
        author: "Maria Organic",
        date: "2023-12-15",
      },
    ],
    specifications: [
      "Capacity: 3 bins x 200L each",
      "Material: Recycled HDPE",
      "Dimensions: 6ft x 3ft x 3ft",
      "Pest Resistant: Yes",
      "Assembly: Required"
    ],
    relatedProducts: [2, 3, 28],
  },
  {
    id: 34,
    image: "https://media.licdn.com/dms/image/v2/D4D12AQHwqzr4So-cuQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1708599338560?e=2147483647&v=beta&t=e8Jt9fa9p15vW-LV4E_Dh-RwSsPHPztzeT8rB0kKuEc",
    title: "Hydroponic Growing System",
    description: "Complete hydroponic growing solution that delivers exceptional yields while conserving water and space. This recirculating deep water culture system features six independent growing sites, each capable of supporting multiple plants depending on variety. The food-grade components ensure safety for edible crop production, while the durable construction guarantees years of reliable operation. The energy-efficient pump and air stone combination provides perfect oxygenation and nutrient delivery to plant roots, eliminating the root zone diseases common in soil cultivation. The expandable design allows you to start small and add more units as your operation grows. With minimal daily maintenance requirements and automated nutrient monitoring, this system is ideal for busy farmers looking to diversify their production. Perfect for leafy greens, herbs, and compact vegetables, allowing profitable year-round cultivation regardless of outdoor growing conditions.",
    price: "18500/kit",
    category: "Hydroponic",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Growing lettuce in half the time with triple the yield per square foot compared to field growing.",
        author: "Samuel Innovative",
        date: "2024-01-20",
      },
    ],
    specifications: [
      "Growing Sites: 6",
      "Reservoir Capacity: 50L",
      "Grow Media: Included",
      "Nutrient Solution: Starter kit included",
      "Power Consumption: 45W",
      "Dimensions: 4ft x 2ft x 1.5ft"
    ],
    relatedProducts: [1, 4, 18],
  },
  {
    id: 35,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4NKof8C9HA1jOyqzngFxJOuMRrVr9-H4g9A&s",
    title: "Commercial Mushroom Growing Kit",
    description: "This professional mushroom cultivation system enables farmers to diversify with high-value specialty mushrooms that command premium market prices. The complete kit includes sterile growing substrate blocks pre-inoculated with premium mushroom spawn varieties including shiitake, oyster, lion's mane, and king trumpet. The specialized growing chambers maintain optimal humidity and temperature while preventing contamination through HEPA filtration. Each substrate block produces multiple harvests over 3-4 months, yielding approximately 2-3 kg of gourmet mushrooms per block. The modular system can be expanded gradually, allowing farmers to scale production based on market demand. Includes comprehensive training materials and access to expert consultation for troubleshooting. An excellent diversification option with minimal space requirements and potential returns of $15-25 per kg for specialty varieties at farmers markets and to restaurants.",
    price: "5500/kit",
    category: "Specialty Crops",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "Started as a side project and now mushrooms are 30% of my farm income with minimal space needed.",
        author: "Jessica Williams",
        date: "2023-10-15",
      },
    ],
    specifications: [
      "Varieties: 4 gourmet types",
      "Yield: 2-3kg per block",
      "Production Cycle: 3-4 months",
    ],
    relatedProducts: [26, 33, 32],
  },
  {
    id: 36,
    image: "https://mygardenandgreenhouse.com/wp-content/uploads/2020/12/Hydro-System-for-Greenhouse-NFT.jpg",
    title: "Complete Hydroponics System",
    description: "This comprehensive hydroponics growing system provides everything needed to establish soilless cultivation for high-value crops. The modular design includes 48 growing positions with individual nutrient delivery channels, automated pH and EC monitoring, and integrated LED grow lights calibrated for optimal plant development. The energy-efficient water circulation system reduces consumption by up to 90% compared to traditional farming while providing consistent nutrient delivery to each plant. Temperature and humidity controls create ideal growing conditions year-round regardless of external weather. Perfect for growing leafy greens, herbs, strawberries, and other high-value crops with faster growth cycles and higher yields than conventional methods. Includes detailed setup guides and ongoing technical support.",
    price: "12000/unit",
    category: "Hydroponics",
    availability: "Pre-order",
    ratings: 4.8,
    reviews: [
      {
        comment: "Revolutionized my small farm business with year-round production.",
        author: "Thomas Zhang",
        date: "2023-09-15",
      },
    ],
    specifications: [
      "Growing Positions: 48",
      "Dimensions: 3m x 2m x 1.8m",
      "Power Consumption: 1200W",
    ],
    relatedProducts: [9, 18, 29],
  },
  {
    id: 37,
    image: "https://images-cdn.ubuy.co.in/654155f8a347bc2b601158b7-luster-leaf-products-luster-leaf-1665.jpg",
    title: "Professional Soil Testing Kit",
    description: "This comprehensive soil analysis system enables farmers to conduct detailed on-site soil evaluations without sending samples to distant laboratories. The kit includes testing equipment for measuring essential soil parameters including pH levels, nitrogen, phosphorus, potassium, and micronutrient concentrations with laboratory-grade accuracy. The digital analyzer provides instant results that can be stored and tracked over time using the companion smartphone application, allowing farmers to monitor soil health trends and make data-driven decisions about fertilization strategies. Each kit contains sufficient materials for over 100 comprehensive soil tests, making it economical for regular monitoring throughout multiple growing seasons. An essential tool for precision agriculture that optimizes input costs while maximizing yield potential through tailored soil management.",
    price: "4500/kit",
    category: "Tools",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Saved thousands on fertilizer by pinpointing exactly what my soil needed.",
        author: "Sara Johnson",
        date: "2023-09-22",
      },
    ],
    specifications: [
      "Tests: pH, NPK, micronutrients",
      "Test Capacity: 100+ samples",
      "Accuracy: ±2% of lab results",
    ],
    relatedProducts: [17, 28, 32],
  },
  {
    id: 38,
    image: "https://www.croptracker.com/images/blog/10_Emerging_AgTech_Innovations/sprayer_drone500.jpg",
    title: "Premium Organic Fertilizer",
    description: "This certified organic fertilizer blend provides complete plant nutrition while improving long-term soil health and microbial activity. Formulated through controlled composting of plant materials, animal manures, and mineral sources, it delivers a balanced spectrum of macro and micronutrients that release gradually throughout the growing season. The proprietary fermentation process eliminates pathogens while preserving beneficial microorganisms that enhance nutrient availability and root development. Unlike synthetic fertilizers, this product builds soil organic matter, improves water retention, and increases carbon sequestration with each application. Extensive field trials demonstrate yield increases of 10-15% compared to conventional organic fertilizers while significantly improving crop quality, flavor, and nutritional content. Ideal for organic farming operations and conventional farmers transitioning to more sustainable practices.",
    price: "1800/ton",
    category: "Fertilizers",
    availability: "In Stock",
    ratings: 4.6,
    reviews: [
      {
        comment: "My vegetables have never tasted better - customers at the farmers market notice the difference.",
        author: "Miguel Rodriguez",
        date: "2023-10-05",
      },
    ],
    specifications: [
      "NPK Ratio: 4-4-4",
      "Organic Certification: USDA Organic",
      "Application Rate: 1 ton/acre",
    ],
    relatedProducts: [2, 3, 28],
  },
  {
    id: 39,
    image: "https://5.imimg.com/data5/ANDROID/Default/2021/5/ZD/WB/VC/20334810/product-jpeg-500x500.jpg",
    title: "Portable Pollination Beehives",
    description: "These specialized beehives are designed specifically for crop pollination services, offering farmers a complete solution for enhancing yield through improved pollination rates. Each unit houses a healthy colony of specially bred honeybees selected for their pollination efficiency and gentle temperament, making them ideal for placement near high-value crops. The innovative hive design features controlled entry points that encourage bees to exit toward target crops, maximizing pollination efficiency while maintaining colony health. The weatherproof construction and integrated pest management system ensure colony survival during seasonal transitions. Research shows these pollination units can increase yields by 20-35% for many fruit, vegetable, and nut crops compared to relying on wild pollinators alone. Units can be rented seasonally or purchased outright with optional maintenance services available.",
    price: "3500/unit",
    category: "Beekeeping",
    availability: "Limited Stock",
    ratings: 4.9,
    reviews: [
      {
        comment: "Doubled my apple orchard yields in the first season of use.",
        author: "Patricia Lee",
        date: "2023-10-12",
      },
    ],
    specifications: [
      "Colony Strength: 8 frames minimum",
      "Service Period: 4-6 weeks",
      "Coverage: 2 acres per hive",
    ],
    relatedProducts: [26, 28, 32],
  },
  {
    id: 40,
    image: "https://www.environdata.com.au/images/gallery/industry-agriculture/Weather-Station-Agriculture-04.jpg",
    title: "Farm Weather Monitoring Station",
    description: "This professional-grade agricultural weather station provides real-time microclimate data essential for optimizing farm operations and reducing weather-related risks. The system continuously monitors temperature, humidity, rainfall, wind speed/direction, solar radiation, and soil moisture at multiple depths, delivering instant alerts and forecasts directly to your smartphone. Advanced algorithms combine local measurements with regional weather models to provide farm-specific forecasts with exceptional accuracy up to 7 days ahead. The solar-powered design with battery backup ensures uninterrupted operation even during power outages, while the rugged construction withstands harsh agricultural environments. Data integration with irrigation controllers and farm management software enables automated decision-making based on current conditions. An essential tool for modern farming that pays for itself through improved timing of planting, harvesting, irrigation, and crop protection activities.",
    price: "7800/unit",
    category: "Technology",
    availability: "In Stock",
    ratings: 4.7,
    reviews: [
      {
        comment: "Warned me about an unexpected frost with enough time to save my entire strawberry crop.",
        author: "David Chen",
        date: "2023-09-30",
      },
    ],
    specifications: [
      "Sensors: 12 environmental parameters",
      "Forecast Range: 7 days",
      "Power: Solar with battery backup",
    ],
    relatedProducts: [17, 18, 30],
  },
  {
    id: 41,
    image: "https://www.e-pots.co.uk/wp-content/uploads/20190418_132010-scaled.jpg",
    title: "Biodegradable Plant Pots",
    description: "Eco-friendly seedling pots made from organic materials. These plantable pots eliminate transplant shock and decompose naturally in soil, adding nutrients as they break down. Perfect for sustainable farming practices and reducing plastic waste. The breathable material promotes healthy root development and prevents root circling. Available in various sizes to accommodate different plant types from herbs to young trees. Each pot features drainage holes to prevent overwatering and root rot. The natural brown color blends seamlessly with garden aesthetics while serving as a visual indicator of planting depth. Suitable for both indoor nurseries and outdoor germination. Stackable design allows for efficient storage and transportation.",
    price: "450/pack of 50",
    category: "Planting",
    availability: "In Stock",
    ratings: 4.8,
    reviews: [
      {
        comment: "Love how these decompose right in the soil. Great for seedlings.",
        author: "Maya Johnson",
        date: "2023-09-15",
      },
    ],
    specifications: [
      "Material: Coconut Coir",
      "Size: 3-inch diameter",
      "Biodegradable: Yes",
    ],
    relatedProducts: [3, 4, 21],
  },
  {
    id: 42,
    image: "https://sourcetrace.com/wp-content/themes/sts-v3/img/ft-sfach.jpg",
    title: "Farm Record Keeping Software",
    description: "Comprehensive digital solution for managing all aspects of farm operations and record keeping. This user-friendly software helps track planting schedules, harvest data, input costs, and sales figures in one centralized platform. The cloud-based system allows access from multiple devices including smartphones, tablets, and computers. Built-in analytics generate visual reports on farm productivity and profitability trends over time. The inventory management feature provides alerts for low supplies and tracks equipment maintenance schedules. Weather integration offers localized forecasts to help plan field operations efficiently. The record keeping complies with organic certification requirements and simplifies audit preparation. Secure data storage with regular backups prevents loss of critical farm information. Annual subscription includes free updates and technical support.",
    price: "3500/year",
    category: "Software",
    availability: "Digital Download",
    ratings: 4.5,
    reviews: [
      {
        comment: "Completely transformed our record keeping. The reports are invaluable for decision making.",
        author: "Thomas Garcia",
        date: "2023-08-30",
      },
    ],
    specifications: [
      "Platform: Web & Mobile",
      "Users: Unlimited",
      "Storage: 50GB",
    ],
    relatedProducts: [20, 24, 25],
  },
  {
    id: 43,
    image: "https://cdn.carmel-apartments.com/system/uploads/fae/image/asset/18861/level_5_best-farmers-markets-downtown-la-echo-park-silver-lake-atwater.jpg",
    title: "Farmers Market Display Kit",
    description: "Complete merchandising solution for farmers selling at local markets and farm stands. This professional display kit includes collapsible tables, adjustable shelving, and branded signage to create an attractive point of sale. The modular components can be configured in multiple layouts to adapt to different selling spaces and product assortments. Weather-resistant materials withstand outdoor conditions while maintaining an appealing presentation. All components pack into a compact carrying case that fits in standard vehicles for easy transportation. The reusable price tag system allows quick updates and clearly communicates product information to customers. Includes a digital scale with built-in price calculator for accurate on-site weighing and pricing. The professional appearance helps establish brand identity and attracts more customers to your market stand. Assembly requires no tools and can be completed in under 15 minutes.",
    price: "7500/kit",
    category: "Marketing",
    availability: "In Stock",
    ratings: 4.8,
    reviews: [
      {
        comment: "Sales increased by 30% after upgrading to this display. Very professional looking.",
        author: "Emma Williams",
        date: "2023-08-25",
      },
    ],
    specifications: [
      "Components: 15 pieces",
      "Setup time: 15 minutes",
      "Weight: 25kg",
    ],
    relatedProducts: [21, 24, 26],
  },
];

export default products;